# Generated by Django 3.0.1 on 2020-01-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_series_usesuccessballast'),
        ('account', '0004_auto_20200102_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='https://cdn.onlinewebfonts.com/svg/img_3594.png', upload_to='users/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='races',
            field=models.ManyToManyField(blank=True, null=True, related_name='drivers', to='website.Race'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='series',
            field=models.ManyToManyField(blank=True, null=True, related_name='drivers', to='website.Series'),
        ),
    ]
