# Generated by Django 3.0.1 on 2020-01-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200103_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='https://i.ibb.co/KGZKQFx/av.jpg', upload_to='users/%Y/%m/%d/'),
        ),
    ]
