# Generated by Django 3.0.1 on 2020-01-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_delete_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seriescars',
            name='car',
        ),
        migrations.RemoveField(
            model_name='seriescars',
            name='series',
        ),
        migrations.AlterModelOptions(
            name='directories',
            options={'verbose_name_plural': 'Directories'},
        ),
        migrations.AlterModelOptions(
            name='qualifications',
            options={'verbose_name_plural': 'Qualifications'},
        ),
        migrations.AlterModelOptions(
            name='qualificationsresults',
            options={'verbose_name_plural': 'Qualifications results'},
        ),
        migrations.AlterModelOptions(
            name='raceresults',
            options={'verbose_name_plural': 'Race results'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name_plural': 'Series'},
        ),
        migrations.AlterModelOptions(
            name='seriesstandings',
            options={'verbose_name_plural': 'Series Standings'},
        ),
        migrations.AddField(
            model_name='series',
            name='cars',
            field=models.ManyToManyField(to='website.Car'),
        ),
        migrations.AlterField(
            model_name='car',
            name='manufacturer',
            field=models.CharField(max_length=200, verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model_name',
            field=models.CharField(max_length=200, verbose_name='Model'),
        ),
        migrations.DeleteModel(
            name='ChallengeCars',
        ),
        migrations.DeleteModel(
            name='SeriesCars',
        ),
    ]
