# Generated by Django 3.0.1 on 2020-01-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20200102_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='isSpecialEvent',
        ),
        migrations.AddField(
            model_name='series',
            name='isSpecialEvent',
            field=models.BooleanField(default=False, verbose_name='Race is special event'),
        ),
    ]
