# Generated by Django 3.0.1 on 2020-01-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_challenge_cars'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Challenge Picture'),
        ),
    ]
