# Generated by Django 3.0.1 on 2020-01-02 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0010_auto_20200102_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='series_picture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Series Picture'),
        ),
        migrations.AlterField(
            model_name='race',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races', to='website.Series'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('body', models.TextField(max_length=1000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('readed_by', models.ManyToManyField(related_name='readed_by', to=settings.AUTH_USER_MODEL)),
                ('reciepents', models.ManyToManyField(related_name='reciepents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
