# Generated by Django 3.0.1 on 2020-01-02 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20200102_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Series Ends at'),
        ),
        migrations.AddField(
            model_name='series',
            name='date_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Series Starts at'),
        ),
    ]
