# Generated by Django 3.0.1 on 2020-01-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20200102_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='useSuccessBallast',
            field=models.BooleanField(default=False, verbose_name='Use Custom Success Ballast'),
        ),
    ]
