# Generated by Django 3.0.1 on 2020-01-03 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rules',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='website.Series'),
        ),
    ]
