# Generated by Django 3.0.1 on 2020-01-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20200103_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='rules',
            name='isRulesDescription',
            field=models.BooleanField(default=False),
        ),
    ]
