# Generated by Django 3.0.1 on 2020-01-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_rules_isrulesdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='series_logo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Series Logo'),
        ),
    ]
