# Generated by Django 3.0.1 on 2020-01-17 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_series_series_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seriesstandings',
            name='qualifications',
        ),
    ]
