# Generated by Django 3.0.1 on 2020-01-17 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_remove_seriesstandings_qualifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Series'),
        ),
    ]
