# Generated by Django 3.0.1 on 2020-01-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_auto_20200117_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='time_acceleration',
        ),
        migrations.AddField(
            model_name='race',
            name='time_acceleration',
            field=models.IntegerField(default=1, verbose_name='Time Acceleration'),
        ),
    ]
