# Generated by Django 3.0.1 on 2020-01-17 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_auto_20200117_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races', to='website.Series'),
        ),
    ]
