# Generated by Django 3.0.1 on 2020-01-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_auto_20200117_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualificationsresults',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='raceresults',
            name='file_name',
        ),
        migrations.AddField(
            model_name='qualificationsresults',
            name='file',
            field=models.FileField(default='', upload_to='./results/qual'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='raceresults',
            name='file',
            field=models.FileField(default='', upload_to='./results/race'),
            preserve_default=False,
        ),
    ]
