# Generated by Django 3.0.1 on 2020-01-17 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_auto_20200117_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualificationsresults',
            name='qualifications',
        ),
        migrations.AddField(
            model_name='qualificationsresults',
            name='race',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='website.Race'),
            preserve_default=False,
        ),
    ]
