# Generated by Django 3.0.1 on 2020-01-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_auto_20200117_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='dnf_get_points',
            field=models.BooleanField(default=False, verbose_name='DNF Get Points'),
        ),
    ]
