# Generated by Django 3.0.1 on 2020-01-21 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_series_dnf_get_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Picture'),
        ),
    ]
