# Generated by Django 3.0.1 on 2020-01-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_car_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='server_password',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Server Password'),
        ),
    ]
