# Generated by Django 3.0.1 on 2020-01-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_series_server_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='server_nr',
            field=models.IntegerField(default='1', verbose_name='Server Number'),
        ),
    ]
