# Generated by Django 3.0.1 on 2020-01-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_challenge_server_nr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Server Number')),
                ('ip', models.TextField(verbose_name='Server Address')),
            ],
        ),
    ]
