# Generated by Django 3.0.1 on 2020-01-21 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_server'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='server_nr',
        ),
        migrations.AddField(
            model_name='challenge',
            name='server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Server'),
        ),
    ]
