# Generated by Django 3.0.1 on 2020-01-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_remove_challenge_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='server_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
