# Generated by Django 3.0.1 on 2020-01-21 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0037_auto_20200121_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='ip_address',
            new_name='address',
        ),
    ]
